name: aif_submission
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  line_icons: ^2.0.1
  firebase: ^9.0.2
  cloud_firestore: ^3.1.13
  badges: ^2.0.2
  google_fonts: ^2.3.2
  lottie: ^1.3.0
  equatable: ^2.0.3

  cupertino_icons: ^1.0.2

  # threeJS_Viewer:
  #   git:
  #     url: https://github.com/ColtonBristow/FlutterThreeJS.git/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/json/bible-kjv/

    - assets/artifacts/hannahMoreDesk/
    - assets/artifacts/NoravankKhachkar/
    - assets/artifacts/tutorialCard/
    - assets/artifacts/woodenBible/
